# Generated by Django 3.0.4 on 2020-03-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=255)),
                ('Slug', models.CharField(max_length=255)),
                ('NewConfirmed', models.IntegerField()),
                ('TotalConfirmed', models.IntegerField()),
                ('NewDeaths', models.IntegerField()),
                ('TotalDeaths', models.IntegerField()),
                ('NewRecovered', models.IntegerField()),
                ('TotalRecovered', models.IntegerField()),
            ],
        ),
    ]
